### ISSUE TITLE
BSD-style license

### ISSUE THREAD

**Issue by mojoaxel** [svrnm/exceldatatables#10]
Hi @lucentlogix @deinonychuscowboy @adael and of most of all @svrnm,

I'm writing you, because you are a contributor to the [svrnm/exceldatatables](//github.com/svrnm/exceldatatables) repository. I choose to open this issue because not all your eMails are available and it's an open source project anyway.

I'm an open source developer myself and first of all I want to thank you for creating this library and making it open-source! That's the way to go!

Currently I'm searching for a simple Excel manipulation library for an commercial project and this code-base looks promising. The project I'm referring to, uses company-specific SQL-Queries inside the PHP code. Because of this it is impossible to make this API public open-source. Because of the 'copyleft' principle of the GPL it is not possible to use or improve svrnm/exceldatatables in an commercial context at  the moment.

Here is my proposal:
**Please release this codebase instead of/or in addition to the GPL license, with some kind of BSD-style license like [MIT](https://opensource.org/licenses/MIT), [Apache](https://opensource.org/licenses/Apache-2.0) or [LGPL](https://opensource.org/licenses/LGPL-3.0). 
In return I'm willing to donate 200 Euros e.g to the [Free-Software-Foundation](https://fsfe.org), the [Open Source Initiative](https://opensource.org/) of any other Non-profit organisation of your choice. Also I'm promising also to give back all improvements I may come up with.**

Please think about it! I considered my proposal a way of giving back to open-source and not working against its ideas!

**Comment by svrnm** [comment]
Hi @mojoaxel,

I would be fine with changing the license. I have to deep dive into this, but I think I would prefer **LGPL**/**Apache* over MIT and also I would prefer a single license over dual-licensing. Please let me know if this makes this still compatible with your requirements. 

I'm also not 100% aware, if I'm still allowed to change the license without agreement from all contributors. I'll check this also, but if all the existing contributors ( @adael @lucentlogix @deinonychuscowboy ) agree with a license change, this would be the easisest approach.

Thanks,
Severin

P.S.: Funny coincident @mojoaxel - as it looks like we live about 1 km apart ;-)

**Comment by deinonychuscowboy** [comment]
I'm fine with a license change. I believe the extent of my contribution is a one-line diff at this point, but for what it's worth, I'd favor LGPL.

**Comment by mojoaxel** [comment]
> Please let me know if this makes this still compatible with your requirements.

I'm good with any solution that allows me to contribute but also to use it in a commercial context without even the fear of "infecting" the corporate code.

After [reading into this](https://bitdepth.thomasrutter.com/2009/01/17/looking-at-the-lgpl-license/) a little, it looks like the LGPL is not perfect for this because it could "infect" code that links to it, as far as I understand. That's why LGPL is usually used for external libraries (like DLLs, Plugins), that get executed as a separated part. **This is not a good fit for runtime languages like JavaScript or PHP**.

After looking into this the best Lizense that keeps the "spiript of the LGPL" without causing problems with dynamic linking would be the [Mozilla Public License](https://en.wikipedia.org/wiki/Mozilla_Public_License). This, together with [Apache](https://en.wikipedia.org/wiki/Apache_License) or [MIT](https://en.wikipedia.org/wiki/MIT_License) would justify this kind of donation for me. I realy hope you understand.

> if all the existing contributors agree with a license change, this would be the easiest approach.

I think so too. Let's wait for their responses...

> as it looks like we live about 1 km apart

That's really an amazing coincidence!! I had no idea!

_(Wenn das mit der lizenz klappt schulde ich dir mal ein Bierchen!)_

**Comment by adael** [comment]
I'll be fine with author's decision. Also my contribution is almost
nothing, so thanks for asking.

2016-12-11 20:37 GMT+01:00 Alexander Wunschik <notifications@github.com>:

**Comment by svrnm** [comment]
All,

I went through a bunch of articles, documents etc. to make up my mind about the question which kind of license I prefer. None of the licenses really covers 100% my personal intent, that people should be able to use my software easily and unworried but at the same time are "encouraged" (read as "forced by the license") to play back immediate changes of the source code to the community. Also, I haven't and hadn't the right amount of legal understanding to foresee all consequences of a chosen license. 
So, I have two options to handle this: I can go through even more sources, discussions and walk down the long path until I have a complete understanding of the matter or I can make a weighed gut-decision:

- Even by enforcing it through the license I can't make sure that people play back der changes, I only can try to encourage them.
- This is (and probably will be) a tiny software project that lives from being reused within larger projects, no matter if they are open- or closed-source.  

Looking at this two criteria and the license choices given, I see a good match with the **Apache License**. 

I will take some more days to see if this current decision is reasonable and I'm also looking for your feedback. **So, if there is no change I will migrate this project to Apache License next week**

Also, since this shouldn't influence the decision process, I ask you @mojoaxel to not donate in behalf of the project or myself.

Thank you all,

**Comment by mojoaxel** [comment]
> I will take some more days to see if this current decision is reasonable and I'm also looking for your feedback.

The Apache License fully fulfills my needs, although I also prefer more restrictive OSS-licenses in general, I'm with you on this, and hope to improve this project in the future.

@svrnm Do you have any suggestion what organisation I should donate to? If not I'll donate 200€ to the fsfe.org as a thank you to the open-source community in general.

**Comment by mojoaxel** [comment]
Any update here?

**Comment by svrnm** [comment]
Yes, I will change the license later today

**Comment by mojoaxel** [comment]
@svrnm Thanks you!
I hope to use/improve it in the next weeks.

```
Donation reference :	FD16348479
Total charge :		200.00 EUR
Beneficiary :		Free Software Foundation Europe e.V.
```
